services:
  client:
    build:
      context: .
      dockerfile: client/.devcontainer/Dockerfile.client
    container_name: client
    volumes:
      - .:/workspace:cached
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_URL_NO_SSL="postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT_INT:-5432}/${POSTGRES_DB:-postgres}"
      - ENV=dev
    command: sleep infinity
    depends_on:
      - server
    networks:
      - homicide-media-tracker_net

  server:
    build:
      context: .
      dockerfile: server/.devcontainer/Dockerfile.server
    container_name: server
    volumes:
      - server_vol:/data/postgresql
      - ./server:/workspace/postgresql:cached
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - ${POSTGRES_PORT_EXT:-5432}:${POSTGRES_PORT_INT:-5432}
    environment:
      - POSTGRES_USER=${POSTGRES_USER-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_PORT_INT=${POSTGRES_PORT_INT:-5432}
    networks:
      - homicide-media-tracker_net

volumes:
  server_vol:

networks:
  homicide-media-tracker_net:
    driver: bridge